python scripts/time_series_feature_extraction.py 'A' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'B' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'C' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'D' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'E' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'F' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'G' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'H' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'I' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'J' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'K' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'L' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'M' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'N' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'O' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'P' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'Q' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'R' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'S' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'T' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'U' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'V' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'W' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'X' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'Y' > ts_log.txt &
python scripts/time_series_feature_extraction.py 'Z' > ts_log.txt &
